### PR TITLE
Added ability to set config in package.json

### PR DESCRIPTION
**Pull request by jtwebb**
New pull request to replace #18 

Error running tests:

```
1) should find all available tests in project
Error: spawn C:\path\to\customizr\bin\customizr ENOENT
```

Once I can get the tests running I can add tests for this feature.

### CODE REVIEW

**Comment by rejas** [comment]
Thanks for the new PR. Cant say why your tests fail, they run fine on my mac... Wil have to wait another week until I get access to my windows machine again...

**Comment by rejas** [comment]
Hi @jtwebb so I fixed it that the tests will run on windows too without errors, so you can proceed now ;-)

**Comment by jtwebb** [comment]
@rejas I've added tests for settings in package.json

**Comment by rejas** [comment]
Awesome. Thx.

**Pull request merged**
