### PR TITLE
Updates for Modernizr v3.7 release

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by rejas** [comment]
@SlexAxton I dont see to have access to this repo, can you check out why?

**Comment by rejas** [comment]
Would love to do some cleanups/updates in this repo @doctyper @SlexAxton @patrickkettner Anyone able to give me write access here too?

**Comment by SlexAxton** [comment]
Should be fixed.

**Comment by rejas** [comment]
Got to bother you again @SlexAxton but could you give me npm publishing rights?

**Comment by SlexAxton** [comment]
sorry, i'm not a publisher on that one either.

**Comment by doctyper** [comment]
@rejas Done, you are now a maintainer.

**Comment by rejas** [comment]
Thx @doctyper worked like a charm. You can't do that for grunt-modernizr by any chance too?

**Pull request merged**
