### PR TITLE
Unable to include Tests wich are specified as an array

### PR DESCRIPTION
**Pull request by Schleuse**
Tries to resolve Issue #43

### CODE REVIEW

**Comment by Schleuse** [comment]
Tests are failung because #42 isn't included

**Comment by rejas** [comment]
Hi @Schleuse would you mind rebasing your PR against the latest develop branch again so we might get it merged an realeased soonish?

**Comment by Schleuse** [comment]
Hi @rejas! I've rebased the current development branch onto this  :smile:

**Comment by rejas** [comment]
Awesome, thx a lot. I'll test it right away :-)

**Comment by rejas** [comment]
LGTM! Would love to see it merged @patrickkettner

**Comment by patrickkettner** [comment]
its fine.

it would be great to get underscore replaced with lodash as the former is more or less dead compared with the later. But I won't block on that.

**Pull request merged**
