### PR TITLE
Fix #56 - Replace underscore with lodash

### LINKED ISSUE #56: Replace underscore with lodash
"it would be great to get underscore replaced with lodash as the former is more or less dead compared with the later" patrickkettner, 2018

### PR DESCRIPTION
**Pull request by Schleuse**
This PR replaces underscore with lodash

### CODE REVIEW

**Comment by rejas** [comment]
LGTM!

**Comment by rejas** [comment]
@rediris  any chance that you got merge rights for this repo?

**Comment by rediris** [comment]
@rejas I don't have merge rights for this repo.

**Comment by rejas** [comment]
oh well, then we got to wait for someone to show up from the original team....

**Pull request merged**
