### PR TITLE
Added ability to set config in package.json

### PR DESCRIPTION
**Pull request by jtwebb**
I forked the repo again to make sure that the errors weren't being caused by me. They're not. From what I can figure out, it looks like the tests are looking for something that Modernizr is no longer supporting. I could be completely wrong, but that's what I can figure out.

### CODE REVIEW

**Comment by rejas** [comment]
Hi @jtwebb still interested in pushing this PR? If so, would you mind adding a test for this feature? Rebasing it agaisnt the latest master branch would get rid of the test-errors by the way.

**Comment by jtwebb** [comment]
@rejas I wouldn't mind pushing this in. I have long since deleted the old repo so I forked it again but still can't run the tests (even before my changes). I'm guessing it's an environment issue so I'll have to wait until I have time to look into it. I'll post the error here in case you happen to know off the top of your head what it is:

```
1) should find all available tests in project
Error: spawn C:\path\to\customizr\bin\customizr ENOENT
```

**Comment by rejas** [comment]
Thx for you rpatience @jtwebb  :-) Could you create a new PR for this so we can take a look at it together?

**Comment by jtwebb** [comment]
@rejas this PR has been replaced by #65.

**Pull request closed without merging**
