### PR TITLE
Fix modernizr build when using customTests key with custom test files

### LINKED ISSUE #22: customTests not working with Modernizr v3
I don't seem to be able to get the `customTests` option to be able to work.

````
TypeError: Cannot read property 'replace' of undefined
    at /Users/joelambert/Projects/Misc/primer-rareloop/node_modules/grunt-modernizr/node_modules/customizr/node_modules/modernizr/lib/build-query.js:22:22
````

I've had a bit of a look and it seems that the v3 version of Modernizr expects all tests to be from the core repository. Might it be better for Customizr to append the contents of files in the `customTests` array to the file produced by the Modernizr build script rather than trying to pass them through?

### PR DESCRIPTION
**Pull request by enwin**
Overall update to fix #22, the ability to add custom test from the user scripts, handle npm version 3 flat directories and update test suite.

Custom tests can be defined with or without the `.js` extension. Path must start from the root of the project;

``` json
"customTests": [
    "test/user-tests/storage",
    "test/user-tests/animationend.js"
]
```

Sorry for mixing fixes but I needed all it to make it work on my computer.

### CODE REVIEW

**Comment by sdussaut** [comment]
+1

**Comment by ctjhoa** [comment]
+1

**Comment by cxq** [comment]
+1

**Comment by signal-intrusion** [comment]
+1

**Comment by dpetton** [comment]
+1

**Comment by PaulinSanselme** [comment]
+1

**Comment by signal-intrusion** [comment]
@doctyper what is the status of this PR? Is there anything we can do to help this get merged?

**Comment by ctjhoa** [comment]
Modernizr team: @aFarkas @bobthecow @doctyper @KuraFire @patrickkettner @paulirish @ryanseddon @SlexAxton @stucox 
This project is clearly not maintained anymore anyone to take care of it ?

**Comment by patrickkettner** [comment]
I just had a child, so I have been offline to care for him. I'll be back to open source in the middle of next week.

**Comment by mcartoixa** [comment]
+1

**Comment by zazaian** [comment]
@ctjhoa I'm trying to clean up some of this work on [my fork](https://github.com/zazaian/customizr). Stay truned as I work to get some of these PRs merged in. Already have the deps cleaned up.

**Comment by rejas** [comment]
@zazaian @enwin hi guys, anyone of you still interested in pushing this PR?

**Pull request closed without merging**
